"""Handwritten code examples for the blog; not generated by Qwen."""
import json


def nested_loop(nums):
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            if nums[i] == nums[j]:
                return True
    return False


def hash_set(nums):
    seen = set()
    for value in nums:
        if value in seen:
            return True
        seen.add(value)
    return False


def sorted_neighbors(nums):
    ordered = sorted(nums)
    return any(ordered[i] == ordered[i-1] for i in range(1, len(ordered)))


def incorrect_familiar_code(nums):
    return len(set(nums)) <= len(nums)  # deliberately wrong: always True


CASES = [([], False), ([1], False), ([1, 2, 3], False),
         ([-1, 0, 1], False), ([10, 20, 30, 40], False),
         ([1, 1], True), ([1, 2, 1], True), ([-1, -1], True),
         ([0, 0, 0], True), ([1, 2, 3, 4, 4], True)]


if __name__ == '__main__':
    result = {}
    for fn in [nested_loop, hash_set, sorted_neighbors, incorrect_familiar_code]:
        passed = sum(fn(nums[:]) == expected for nums, expected in CASES)
        result[fn.__name__] = dict(passed=passed, total=len(CASES), fraction=passed/len(CASES))
    assert all(result[name]['passed'] == 10 for name in ['nested_loop', 'hash_set', 'sorted_neighbors'])
    assert result['incorrect_familiar_code']['passed'] == 5
    print(json.dumps(result, ensure_ascii=False, indent=2))
